spring:
  datasource:
    url: jdbc:mysql:///student10
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:com/qianfeng/dao/*.xml
  type-aliases-package: com.qianfeng.entity
